version: '3.9'


services:
    web:
        container_name: bde-web
        image: bde-cesi-nancy/web
        build:
            context: .
            dockerfile: Dockerfile.web
        hostname: bde-web
        networks:
            - bde-web


networks:
    bde-web:
        external: true
