version: '3.9'


services:
    web:
        container_name: bde-web
        image: bde-cesi-nancy/web
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
            target: web
        hostname: bde-web
        networks:
            - web
        environment:
            PUBLIC_WEB_URL: "${PUBLIC_WEB_URL}"
            PUBLIC_DIRECTUS_URL: "${PUBLIC_DIRECTUS_URL}"
            PUBLIC_VAPID_KEY: "${PUBLIC_VAPID_KEY}"
            DIRECTUS_LOCAL_URL: "${DIRECTUS_LOCAL_URL}"
            REFRESH_TOKEN_COOKIE_DOMAIN: "${REFRESH_TOKEN_COOKIE_DOMAIN}"

    directus:
        container_name: bde-directus
        image: bde-cesi-nancy/directus
        #command: "npx directus bootstrap" # TO UNCOMMENT ON FIRST RUN TO INITIALIZE DIRECTUS - may crash, then comment back and start again
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
            target: directus
            args:
                DIRECTUS_VERSION: "${DIRECTUS_VERSION}"
        hostname: bde-directus
        depends_on:
            - mysql
            - redis
        networks:
            - web
            - internal
        volumes:
            - directus-uploads:/directus/uploads
            -   type: bind
                source: ./directus/schema.yaml
                target: /directus/schema/schema.yaml
        environment:
            KEY: "${DIRECTUS_KEY}"
            SECRET: "${DIRECTUS_SECRET}"
            GRAPHQL_INTROSPECTION: "false"
            MAX_RELATIONAL_DEPTH: "5"

            DB_CLIENT: "mysql"
            DB_HOST: "mysql"
            DB_PORT: "3306"
            DB_DATABASE: "directus"
            DB_USER: "${MYSQL_USER}"
            DB_PASSWORD: "${MYSQL_PASSWORD}"

            CACHE_ENABLED: "true"
            CACHE_STORE: "redis"
            REDIS: "redis://redis:6379"
            CACHE_AUTO_PURGE: "true"

            ADMIN_EMAIL: "${ADMIN_EMAIL}"
            ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
            AUTH_DISABLE_DEFAULT: "true"

            AUTH_PROVIDERS: "microsoft"
            AUTH_MICROSOFT_DRIVER: "openid"
            AUTH_MICROSOFT_CLIENT_ID: "${AUTH_MICROSOFT_CLIENT_ID}"
            AUTH_MICROSOFT_CLIENT_SECRET: "${AUTH_MICROSOFT_CLIENT_SECRET}"
            AUTH_MICROSOFT_ISSUER_URL: "https://login.microsoftonline.com/organizations/v2.0/.well-known/openid-configuration"
            AUTH_MICROSOFT_SCOPE: "openid profile email"
            AUTH_MICROSOFT_IDENTIFIER_KEY: "sub"
            AUTH_MICROSOFT_ICON: "microsoft"
            AUTH_MICROSOFT_ALLOW_PUBLIC_REGISTRATION: "true"
            AUTH_MICROSOFT_DEFAULT_ROLE_ID: "71df4bc0-8079-4d6d-b7e6-5d69929f4269"

            PUBLIC_URL: "${PUBLIC_DIRECTUS_URL}"

            CORS_ENABLED: "true"
            CORS_ORIGIN: "${PUBLIC_WEB_URL}"
            IP_CUSTOM_HEADER: "${IP_CUSTOM_HEADER}"
            REFRESH_TOKEN_COOKIE_SECURE: "true"
            REFRESH_TOKEN_COOKIE_SAME_SITE: "None"
            REFRESH_TOKEN_COOKIE_DOMAIN: "${REFRESH_TOKEN_COOKIE_DOMAIN}"

            HELLO_ASSO_CLIENT: "${HELLO_ASSO_CLIENT}"
            HELLO_ASSO_SECRET: "${HELLO_ASSO_SECRET}"
            HELLO_ASSO_ORGANIZATION: "${HELLO_ASSO_ORGANIZATION}"
            HELLO_ASSO_ALLOWED_MEMBERSHIPS_FORMS: "${HELLO_ASSO_ALLOWED_MEMBERSHIPS_FORMS}"

            PUBLIC_VAPID_KEY: "${PUBLIC_VAPID_KEY}"
            PRIVATE_VAPID_KEY: "${PRIVATE_VAPID_KEY}"
            VAPID_SUBJECT: "${VAPID_SUBJECT}"

    mysql:
        container_name: bde-mysql
        image: mysql:8.0.33-oracle
        restart: unless-stopped
        hostname: bde-mysql
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - internal
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "directus"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

    redis:
        container_name: bde-redis
        image: redis:alpine
        restart: unless-stopped
        hostname: bde-redis
        networks:
            - internal


networks:
    web:
        name: bde-web
        external: true
    internal:
        name: bde-internal
        external: false


volumes:
    mysql:
        name: "bde-mysql"
        external: true
    directus-uploads:
        name: "bde-uploads"
        external: true
