FROM node:16.16-alpine AS builder

RUN wget -O - https://get.pnpm.io/v6.16.js | node - add --global pnpm

WORKDIR /build
COPY pnpm-lock.yaml .

RUN pnpm fetch

ADD . ./
RUN pnpm install -r --offline

WORKDIR /build/web
RUN pnpm build


FROM node:16.16-alpine

WORKDIR /app
COPY --from=builder /build/web/build build
COPY --from=builder /build/web/package.json .

CMD ["/bin/sh", "-c", "node build"]
