import { MigrationConfig } from '@types';

const BUREAU_ROLE = '87ab5db5-589a-4834-8233-6cd3ca79aae6';

export default {
    async up(knex) {
        await knex('directus_roles').insert({
            id: BUREAU_ROLE,
            name: 'Bureau',
            icon: 'local_police',
            description: 'Utilisateur membre du bureau, avec des accès complets en lecture et des accès avancés en écriture',
            ip_access: null,
            enforce_tfa: 0,
            admin_access: 0,
            app_access: 1,
        });

        await knex('directus_permissions').insert([
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'directus_files',
                action: 'create',
                permissions: {},
                validation: null,
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'directus_files',
                action: 'read',
                permissions: {},
                validation: null,
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'directus_files',
                action: 'update',
                permissions: { _and: [ { uploaded_by: { _contains: '$CURRENT_USER' } } ] },
                validation: null,
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'directus_files',
                action: 'delete',
                permissions: { _and: [ { uploaded_by: { _contains: '$CURRENT_USER' } } ] },
                validation: null,
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'directus_dashboards',
                action: 'read',
                permissions: {},
                validation: null,
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'directus_panels',
                action: 'read',
                permissions: {},
                validation: null,
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'directus_folders',
                action: 'create',
                permissions: {},
                validation: null,
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'directus_folders',
                action: 'read',
                permissions: {},
                validation: null,
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'directus_users',
                action: 'read',
                permissions: {},
                validation: null,
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'directus_users',
                action: 'update',
                permissions: null,
                validation: null,
                presets: null,
                fields: 'language,theme',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'directus_roles',
                action: 'read',
                permissions: {},
                validation: null,
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'directus_shares',
                action: 'read',
                permissions: { _or: [ { role: { _eq: '$CURRENT_ROLE' } }, { role: { _null: true } } ] },
                validation: null,
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'directus_flows',
                action: 'read',
                permissions: { trigger: { _eq: 'manual' } },
                validation: null,
                presets: null,
                fields: 'id,name,icon,color,options,trigger',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'cesi_accounts',
                action: 'read',
                permissions: {},
                validation: {},
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'cesi_accounts_updates',
                action: 'read',
                permissions: {},
                validation: {},
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'clubs',
                action: 'read',
                permissions: {},
                validation: {},
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'clubs',
                action: 'create',
                permissions: {},
                validation: {},
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'clubs',
                action: 'update',
                permissions: {},
                validation: {},
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'contact',
                action: 'read',
                permissions: {},
                validation: {},
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'contact',
                action: 'update',
                permissions: null,
                validation: null,
                presets: null,
                fields: 'status',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'events',
                action: 'create',
                permissions: {},
                validation: {},
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'events',
                action: 'read',
                permissions: {},
                validation: {},
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'events',
                action: 'update',
                permissions: {},
                validation: {},
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'helloasso_logs',
                action: 'read',
                permissions: {},
                validation: {},
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'memberships',
                action: 'read',
                permissions: {},
                validation: {},
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'organization_chart',
                action: 'read',
                permissions: {},
                validation: {},
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'organization_chart',
                action: 'create',
                permissions: {},
                validation: {},
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'organization_chart',
                action: 'update',
                permissions: {},
                validation: {},
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'promotions',
                action: 'read',
                permissions: {},
                validation: {},
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'recruitment',
                action: 'read',
                permissions: {},
                validation: {},
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'recruitment',
                action: 'create',
                permissions: {},
                validation: {},
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'recruitment',
                action: 'update',
                permissions: {},
                validation: {},
                presets: null,
                fields: '*',
            },
            {
                role: '87ab5db5-589a-4834-8233-6cd3ca79aae6',
                collection: 'unauthorized_logins',
                action: 'read',
                permissions: {},
                validation: {},
                presets: null,
                fields: '*',
            },
        ]);
    },
    async down(knex) {
        await knex('directus_permissions').where({ role: BUREAU_ROLE }).del();
        await knex('directus_roles').where({ id: BUREAU_ROLE }).del();
    },
} as MigrationConfig;
