version: 1
directus: 9.16.1
collections:
  - collection: accounts
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: accounts
      color: null
      display_template: null
      group: null
      hidden: false
      icon: group
      item_duplication_fields: null
      note: null
      singleton: false
      sort: 1
      sort_field: null
      translations:
        - language: fr-FR
          translation: Comptes
      unarchive_value: null
    schema: null
  - collection: cesi_accounts
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: cesi_accounts
      color: null
      display_template: '{{name}}'
      group: accounts
      hidden: false
      icon: admin_panel_settings
      item_duplication_fields: null
      note: null
      singleton: false
      sort: 1
      sort_field: null
      translations:
        - plural: Comptes CESI
          language: fr-FR
          singular: Compte CESI
          translation: Comptes CESI
      unarchive_value: null
    schema:
      collation: utf8mb4_0900_ai_ci
      comment: ''
      engine: InnoDB
      name: cesi_accounts
      schema: directus
  - collection: promotions
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: promotions
      color: null
      display_template: '{{name}}'
      group: accounts
      hidden: false
      icon: format_list_bulleted
      item_duplication_fields: null
      note: null
      singleton: false
      sort: 2
      sort_field: null
      translations:
        - plural: Promotions
          language: fr-FR
          singular: Promotion
          translation: Promotions
      unarchive_value: null
    schema:
      collation: utf8mb4_0900_ai_ci
      comment: ''
      engine: InnoDB
      name: promotions
      schema: directus
fields:
  - collection: cesi_accounts
    field: date_created
    meta:
      collection: cesi_accounts
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_created
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 3
      special:
        - date-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: timestamp
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: date_created
      numeric_precision: null
      numeric_scale: null
      table: cesi_accounts
    type: timestamp
  - collection: cesi_accounts
    field: date_updated
    meta:
      collection: cesi_accounts
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_updated
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 5
      special:
        - date-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: timestamp
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: date_updated
      numeric_precision: null
      numeric_scale: null
      table: cesi_accounts
    type: timestamp
  - collection: cesi_accounts
    field: email
    meta:
      collection: cesi_accounts
      conditions: null
      display: null
      display_options: null
      field: email
      group: null
      hidden: false
      interface: input
      note: null
      options:
        iconRight: email
        trim: true
      readonly: false
      required: true
      sort: 6
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: varchar
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: false
      is_unique: true
      max_length: 255
      name: email
      numeric_precision: null
      numeric_scale: null
      table: cesi_accounts
    type: string
  - collection: cesi_accounts
    field: id
    meta:
      collection: cesi_accounts
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options:
        iconRight: key
      readonly: true
      required: false
      sort: 1
      special:
        - uuid
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: char
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: false
      max_length: 36
      name: id
      numeric_precision: null
      numeric_scale: null
      table: cesi_accounts
    type: uuid
  - collection: cesi_accounts
    field: name
    meta:
      collection: cesi_accounts
      conditions: null
      display: null
      display_options: null
      field: name
      group: null
      hidden: false
      interface: input
      note: null
      options:
        iconRight: person
        trim: true
      readonly: false
      required: true
      sort: 7
      special: null
      translations:
        - language: fr-FR
          translation: Nom
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: varchar
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: name
      numeric_precision: null
      numeric_scale: null
      table: cesi_accounts
    type: string
  - collection: cesi_accounts
    field: promotion
    meta:
      collection: cesi_accounts
      conditions: null
      display: null
      display_options: null
      field: promotion
      group: null
      hidden: false
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{name}} ({{code}})'
      readonly: false
      required: true
      sort: 8
      special:
        - m2o
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: varchar
      default_value: null
      foreign_key_column: code
      foreign_key_table: promotions
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: promotion
      numeric_precision: null
      numeric_scale: null
      table: cesi_accounts
    type: string
  - collection: cesi_accounts
    field: user_created
    meta:
      collection: cesi_accounts
      conditions: null
      display: user
      display_options: null
      field: user_created
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      sort: 2
      special:
        - user-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: char
      default_value: null
      foreign_key_column: id
      foreign_key_table: directus_users
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 36
      name: user_created
      numeric_precision: null
      numeric_scale: null
      table: cesi_accounts
    type: string
  - collection: cesi_accounts
    field: user_updated
    meta:
      collection: cesi_accounts
      conditions: null
      display: user
      display_options: null
      field: user_updated
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      sort: 4
      special:
        - user-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: char
      default_value: null
      foreign_key_column: id
      foreign_key_table: directus_users
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 36
      name: user_updated
      numeric_precision: null
      numeric_scale: null
      table: cesi_accounts
    type: string
  - collection: promotions
    field: code
    meta:
      collection: promotions
      conditions: null
      display: null
      display_options: null
      field: code
      group: null
      hidden: false
      interface: input
      note: null
      options:
        iconLeft: null
        iconRight: key
        softLength: 8
        trim: true
      readonly: false
      required: false
      sort: 5
      special: null
      translations:
        - language: fr-FR
          translation: Code analytique
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: varchar
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: false
      max_length: 255
      name: code
      numeric_precision: null
      numeric_scale: null
      table: promotions
    type: string
  - collection: promotions
    field: date_created
    meta:
      collection: promotions
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_created
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 2
      special:
        - date-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: timestamp
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: date_created
      numeric_precision: null
      numeric_scale: null
      table: promotions
    type: timestamp
  - collection: promotions
    field: date_updated
    meta:
      collection: promotions
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_updated
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 4
      special:
        - date-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: timestamp
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: date_updated
      numeric_precision: null
      numeric_scale: null
      table: promotions
    type: timestamp
  - collection: promotions
    field: name
    meta:
      collection: promotions
      conditions: null
      display: null
      display_options: null
      field: name
      group: null
      hidden: false
      interface: input
      note: null
      options:
        iconLeft: null
        iconRight: label
        trim: true
      readonly: false
      required: true
      sort: 6
      special: null
      translations:
        - language: fr-FR
          translation: Nom
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: varchar
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: name
      numeric_precision: null
      numeric_scale: null
      table: promotions
    type: string
  - collection: promotions
    field: user_created
    meta:
      collection: promotions
      conditions: null
      display: user
      display_options: null
      field: user_created
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      sort: 1
      special:
        - user-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: char
      default_value: null
      foreign_key_column: id
      foreign_key_table: directus_users
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 36
      name: user_created
      numeric_precision: null
      numeric_scale: null
      table: promotions
    type: string
  - collection: promotions
    field: user_updated
    meta:
      collection: promotions
      conditions: null
      display: user
      display_options: null
      field: user_updated
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      sort: 3
      special:
        - user-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: char
      default_value: null
      foreign_key_column: id
      foreign_key_table: directus_users
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 36
      name: user_updated
      numeric_precision: null
      numeric_scale: null
      table: promotions
    type: string
relations:
  - collection: cesi_account
    field: promotion
    meta:
      junction_field: null
      many_collection: cesi_account
      many_field: promotion
      one_allowed_collections: null
      one_collection: promotions
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: promotions
    schema: null
  - collection: cesi_account
    field: user_created
    meta:
      junction_field: null
      many_collection: cesi_account
      many_field: user_created
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: directus_users
    schema: null
  - collection: cesi_account
    field: user_updated
    meta:
      junction_field: null
      many_collection: cesi_account
      many_field: user_updated
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: directus_users
    schema: null
  - collection: cesi_accounts
    field: promotion
    meta:
      junction_field: null
      many_collection: cesi_accounts
      many_field: promotion
      one_allowed_collections: null
      one_collection: promotions
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: promotions
    schema:
      column: promotion
      constraint_name: cesi_accounts_promotion_foreign
      foreign_key_column: code
      foreign_key_table: promotions
      on_delete: SET NULL
      on_update: NO ACTION
      table: cesi_accounts
  - collection: cesi_accounts
    field: user_created
    meta: null
    related_collection: directus_users
    schema:
      column: user_created
      constraint_name: cesi_account_user_created_foreign
      foreign_key_column: id
      foreign_key_table: directus_users
      on_delete: NO ACTION
      on_update: NO ACTION
      table: cesi_accounts
  - collection: cesi_accounts
    field: user_updated
    meta: null
    related_collection: directus_users
    schema:
      column: user_updated
      constraint_name: cesi_account_user_updated_foreign
      foreign_key_column: id
      foreign_key_table: directus_users
      on_delete: NO ACTION
      on_update: NO ACTION
      table: cesi_accounts
  - collection: promotions
    field: user_created
    meta:
      junction_field: null
      many_collection: promotions
      many_field: user_created
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: directus_users
    schema:
      column: user_created
      constraint_name: promotions_user_created_foreign
      foreign_key_column: id
      foreign_key_table: directus_users
      on_delete: NO ACTION
      on_update: NO ACTION
      table: promotions
  - collection: promotions
    field: user_updated
    meta:
      junction_field: null
      many_collection: promotions
      many_field: user_updated
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: directus_users
    schema:
      column: user_updated
      constraint_name: promotions_user_updated_foreign
      foreign_key_column: id
      foreign_key_table: directus_users
      on_delete: NO ACTION
      on_update: NO ACTION
      table: promotions
