version: 1
directus: 9.16.1
collections:
  - collection: accounts
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: accounts
      color: null
      display_template: null
      group: null
      hidden: false
      icon: group
      item_duplication_fields: null
      note: null
      singleton: false
      sort: 1
      sort_field: null
      translations:
        - language: fr-FR
          translation: Comptes
      unarchive_value: null
    schema: null
  - collection: cesi_accounts
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: cesi_accounts
      color: null
      display_template: '{{name}}'
      group: accounts
      hidden: false
      icon: admin_panel_settings
      item_duplication_fields: null
      note: null
      singleton: false
      sort: 1
      sort_field: null
      translations:
        - plural: comptes CESI
          language: fr-FR
          singular: compte CESI
          translation: Compte CESI
      unarchive_value: null
    schema:
      collation: utf8mb4_0900_ai_ci
      comment: ''
      engine: InnoDB
      name: cesi_accounts
      schema: directus
  - collection: promotions
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: promotions
      color: null
      display_template: '{{name}} ({{code}})'
      group: accounts
      hidden: false
      icon: format_list_bulleted
      item_duplication_fields: null
      note: null
      singleton: false
      sort: 2
      sort_field: null
      translations:
        - plural: promotions
          language: fr-FR
          singular: promotion
          translation: Promotions
      unarchive_value: null
    schema:
      collation: utf8mb4_0900_ai_ci
      comment: ''
      engine: InnoDB
      name: promotions
      schema: directus
fields:
  - collection: cesi_accounts
    field: email
    meta:
      collection: cesi_accounts
      conditions: null
      display: null
      display_options: null
      field: email
      group: null
      hidden: false
      interface: input
      note: null
      options:
        iconRight: email
        trim: true
      readonly: false
      required: true
      sort: null
      special: null
      translations:
        - language: fr-FR
          translation: Email
      validation:
        _and:
          - email:
              _contains: '@viacesi.fr'
      validation_message: L'email doit être une adresse viacesi
      width: full
    schema:
      comment: ''
      data_type: varchar
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: true
      max_length: 127
      name: email
      numeric_precision: null
      numeric_scale: null
      table: cesi_accounts
    type: string
  - collection: cesi_accounts
    field: id
    meta:
      collection: cesi_accounts
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special:
        - uuid
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: char
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: false
      max_length: 36
      name: id
      numeric_precision: null
      numeric_scale: null
      table: cesi_accounts
    type: uuid
  - collection: cesi_accounts
    field: name
    meta:
      collection: cesi_accounts
      conditions: null
      display: null
      display_options: null
      field: name
      group: null
      hidden: false
      interface: input
      note: null
      options:
        iconRight: person
      readonly: false
      required: true
      sort: null
      special: null
      translations:
        - language: fr-FR
          translation: Nom
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: varchar
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 63
      name: name
      numeric_precision: null
      numeric_scale: null
      table: cesi_accounts
    type: string
  - collection: cesi_accounts
    field: promotion
    meta:
      collection: cesi_accounts
      conditions: null
      display: related-values
      display_options: null
      field: promotion
      group: null
      hidden: false
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{name}} ({{code}})'
      readonly: false
      required: true
      sort: null
      special:
        - m2o
      translations:
        - language: fr-FR
          translation: Promotion
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: varchar
      default_value: null
      foreign_key_column: code
      foreign_key_table: promotions
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: promotion
      numeric_precision: null
      numeric_scale: null
      table: cesi_accounts
    type: string
  - collection: promotions
    field: code
    meta:
      collection: promotions
      conditions: null
      display: raw
      display_options: null
      field: code
      group: null
      hidden: false
      interface: input
      note: null
      options:
        font: monospace
        iconRight: key
        softLength: 8
        trim: true
      readonly: false
      required: false
      sort: null
      special: null
      translations: null
      validation:
        _and:
          - code:
              _starts_with: NY
      validation_message: Le code analytique doit être du CESI Nancy
      width: full
    schema:
      comment: ''
      data_type: varchar
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: false
      max_length: 255
      name: code
      numeric_precision: null
      numeric_scale: null
      table: promotions
    type: string
  - collection: promotions
    field: name
    meta:
      collection: promotions
      conditions: null
      display: null
      display_options: null
      field: name
      group: null
      hidden: false
      interface: input
      note: null
      options:
        iconRight: label
        trim: true
      readonly: false
      required: false
      sort: null
      special: null
      translations:
        - language: fr-FR
          translation: Nom
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: varchar
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 127
      name: name
      numeric_precision: null
      numeric_scale: null
      table: promotions
    type: string
relations:
  - collection: cesi_accounts
    field: promotion
    meta:
      junction_field: null
      many_collection: cesi_accounts
      many_field: promotion
      one_allowed_collections: null
      one_collection: promotions
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: promotions
    schema:
      column: promotion
      constraint_name: cesi_accounts_promotion_foreign
      foreign_key_column: code
      foreign_key_table: promotions
      on_delete: SET NULL
      on_update: NO ACTION
      table: cesi_accounts
